# Generated by Django 5.0.1 on 2025-04-13 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(max_length=250)),
                ('disease', models.CharField(choices=[('common_rust', 'Common Rust'), ('healthy', 'Healthy'), ('other_disease', 'Other disease')], max_length=20)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
