# Generated by Django 5.0.1 on 2025-04-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('disease', models.CharField(choices=[('common_rust', 'common_rust'), ('healthy', 'healthy'), ('other_disease', 'other_disease')], max_length=20)),
                ('resource_type', models.CharField(choices=[('article', 'article'), ('video', 'video')], max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
