# Generated by Django 5.2 on 2025-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationresource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='educationresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='educationresource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='educationresource',
            name='disease',
            field=models.CharField(choices=[('common_rust', 'Common Rust'), ('healthy', 'Healthy'), ('other_disease', 'Other disease')], max_length=20),
        ),
        migrations.AlterField(
            model_name='educationresource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video')], max_length=20),
        ),
    ]
